apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-product-pvc
  namespace: qlysanbong
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product
  namespace: qlysanbong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-product
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-product
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: product_db
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-product-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-product
  namespace: qlysanbong
spec:
  selector:
    app: mysql-product
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
