apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-service
  namespace: qlysanbong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-service
  template:
    metadata:
      labels:
        app: supplier-service
    spec:
      containers:
        - name: supplier-service
          image: supplier-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-supplier:3306/supplier_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  namespace: qlysanbong
spec:
  type: NodePort
  selector:
    app: supplier-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
